version: "3.9"

services:
  db:
    image: postgres:10.11
    container_name: metron_db
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - 'variables.env'
  web:
    build: .
    command: poetry run python -m metron_sites
    volumes:
      - profile-data:/vol/web
      - static-data:/vol/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - Environment=test
    env_file:
      - 'variables.env'

    depends_on:
      - db
    restart: always

  pgadmin:
    container_name: metron_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=quam.kponton@gmail.com # ${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=admin # ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  db:
    driver: local
  pgdata:
  static-data:
  profile-data:
